/**
 * The Pentix mark: a side-profile pushup figure (the app's whole economy is
 * goals → pushups). Rendered as a CSS mask of /icons/mark.png filled with the
 * theme primary, so it turns deep green in light mode and mint in dark mode.
 * mark.png is the tight-cropped figure (~2:1) generated by scripts/generate-icons.mjs.
 */
const MARK_ASPECT = 348 / 172;

export function PentixMark({
  size = 22,
  className = "",
}: {
  size?: number;
  className?: string;
}) {
  return (
    <span
      role="img"
      aria-label="Pentix"
      className={`inline-block shrink-0 ${className}`}
      style={{
        height: size,
        width: size * MARK_ASPECT,
        backgroundColor: "var(--primary)",
        WebkitMaskImage: "url(/icons/mark.png)",
        maskImage: "url(/icons/mark.png)",
        WebkitMaskRepeat: "no-repeat",
        maskRepeat: "no-repeat",
        WebkitMaskPosition: "center",
        maskPosition: "center",
        WebkitMaskSize: "contain",
        maskSize: "contain",
      }}
    />
  );
}

export function PentixLogo({ size = 26 }: { size?: number }) {
  return (
    <span className="inline-flex items-center gap-2">
      <PentixMark size={size * 0.92} />
      <span
        className="font-semibold tracking-tight text-ink"
        style={{ fontSize: size * 0.72 }}
      >
        Pentix
      </span>
    </span>
  );
}
